export const MISSING_FIELDS_REQUIRED = "MISSING_FIELDS_REQUIRED";
export const NOT_FOUND = "NOT_FOUND";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_PASSWORD_LENGTH = "INVALID_PASSWORD_LENGTH";
export const DUPLICATE_RECORD = "DUPLICATE_RECORD";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const INVALID_TOKEN = "INVALID_TOKEN";
